"""init_existing_db

Revision ID: 2eb9780da61a
Revises:
Create Date: 2026-09-09 22:47:58.097278

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2eb9780da61a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
