"""rename table employee to user, delete attribute keycloak_id

Revision ID: b293e7eb66da
Revises: d8bab20e46aa
Create Date: 2026-09-27 20:27:26.039448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b293e7eb66da"
down_revision: str | Sequence[str] | None = "d8bab20e46aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"], name="user_department_id_fk"),
        sa.PrimaryKeyConstraint("id", name="user_pk"),
        sa.UniqueConstraint("email", name="user_email_u"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name="user_role_role_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_role_user_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name="user_role_pk"),
    )
    op.create_index("idx_user_role_role_id", "user_role", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_role",
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name=op.f("employee_role_employee_id_fk"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("employee_role_role_id_fk"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("employee_id", "role_id", name=op.f("employee_role_pk")),
    )
    op.create_index(op.f("idx_employee_role_role_id"), "employee_role", ["role_id"], unique=False)
    op.create_table(
        "employee",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=2147483647,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("first_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("keycloak_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("department_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["department.id"], name=op.f("employee_department_id_fk")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("employee_pk")),
        sa.UniqueConstraint(
            "email",
            name=op.f("employee_email_u"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "keycloak_id",
            name=op.f("employee_keycloak_u"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index("idx_user_role_role_id", table_name="user_role")
    op.drop_table("user_role")
    op.drop_table("user")
    # ### end Alembic commands ###
