"""changed sds from bool to str (path to file)

Revision ID: d8bab20e46aa
Revises: 2eb9780da61a
Create Date: 2026-09-10 14:04:43.876589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bab20e46aa'
down_revision: Union[str, Sequence[str], None] = '2eb9780da61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('substance', 'sds',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               comment='Cesta k souboru SDS na serveru',
               existing_comment='true, if sds is saved on server',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('substance', 'sds',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               comment='true, if sds is saved on server',
               existing_comment='Cesta k souboru SDS na serveru',
               existing_nullable=True)
    # ### end Alembic commands ###
