"""add role_id attribute to table user

Revision ID: e291c56fac82
Revises: f67c82717d87
Create Date: 2026-09-27 21:26:24.114067

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e291c56fac82"
down_revision: str | Sequence[str] | None = "f67c82717d87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key(op.f("fk_user_role_id_role"), "user", "role", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_user_role_id_role"), "user", type_="foreignkey")
    op.drop_column("user", "role_id")
    # ### end Alembic commands ###
