"""add password attribute to table user

Revision ID: ebf6b2501ba3
Revises: b293e7eb66da
Create Date: 2026-09-27 21:05:11.588865

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebf6b2501ba3"
down_revision: str | Sequence[str] | None = "b293e7eb66da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_employee_role_role_id"), table_name="employee_role")
    op.drop_table("employee_role")
    op.add_column("user", sa.Column("password", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    op.create_table(
        "employee_role",
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("employee_role_role_id_fk"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("employee_id", "role_id", name=op.f("employee_role_pk")),
    )
    op.create_index(op.f("idx_employee_role_role_id"), "employee_role", ["role_id"], unique=False)
    # ### end Alembic commands ###
