"""add is_verified attribute to table user

Revision ID: f67c82717d87
Revises: 28a088ff1c55
Create Date: 2026-09-27 21:07:04.319996

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f67c82717d87"
down_revision: str | Sequence[str] | None = "28a088ff1c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
